### ISSUE TITLE
Bug: `scrollBy` calls succeeding `moveTo` calls are negated by `moveTo` calls

### ISSUE THREAD

**Issue by vkhoroshko** [FXMisc/RichTextFX#389] opened 2016-11-10 09:24 UTC
Hello,

We're using **CodeArea** and trying to combine **moveTo** operation and **setEstimatedScrollY** operation after that.  
 Example:  
```
codeArea.moveTo(startParagraph, 0);
codeArea.setEstimatedScrollY(startParagraphYOffset + delta);
```

We need to scroll a little to give more context to a user (i.e. few lines after caret position) cause when **VirtualizedScrollPane** is used and current scroll postion is at the top - **moveTo** just scrolls to specified paragraph that will be at the bottom of visible area (i.e. no lines after that).

If I comment **moveTo** instruction - than second instruction works. As I understand - we need to wait till moveTo really worked and only try to set scroll position after that. We tried ``Platform.runLater`` but without success.

Could you please suggest whether there is a possible solution to this issue?  

Thanks in advance.

**Comment by JordanMartinez** [comment] 2016-11-10 16:16
Which version are you using?

Could you `moveTo` a paragraph or two farther down and then back up? That'll work for most of your use cases except for the last paragraph line, which wouldn't be able to scroll farther down anyways.

`VirtualizedScrollPane` has `scrollBy(double delta)` but it's not exposed as an API in any version right now and I haven't done any bugfixing until #356 gets merged.

**Comment by vkhoroshko** [comment] 2016-11-11 09:01
Hello Jordan,

Thank you for the response. We're using the **0.7-M2** version.  
We tried your suggestion also:  
```
codeArea.moveTo(indexRange.getEnd(), 0);
codeArea.moveTo(indexRange.getStart(), 0);
```
Unfortunately, it doesn't work. It still works like only second instruction is active (i.e. move to start). 

The only way we could make it working is to use a timer with 100 milliseconds delay (just the minimum number that worked correctly in our case):
```
codeArea.moveTo(indexRange.getEnd(), 0);       

new Timer().schedule(new TimerTask() {
     public void run() {
          Platform.runLater(() -> {
              codeArea.moveTo(indexRange.getStart(), 0);
           });
      }
}, 100);
```
With this timer trick the **setEstimatedScrollY** instruction works just fine also - and this is more preferable solution  cause with two **moveTo** operations you also need to hide a caret temporary (i.e. for user to do not notice that caret is moved twice).

But we don't like this solution really because it's unclear what's the delay should really be.  

Maybe we can listen to a specific event to be acknowledged when **moveTo** operation completes?   
We tried to play with listener for the **beingUpdated** property but without success.

**Comment by JordanMartinez** [comment] 2016-11-11 15:41
Mmm... It sounds like exposing the aforementioned API for `scrollBy` would be the best thing to do. Anything else I propose or you come up with will only be a workaround for that method.

**Comment by JordanMartinez** [comment] 2016-11-11 16:34
After Tomas merges my code in Flowless, I can update #391 to include more of those additional scrolling methods.

**Comment by JordanMartinez** [comment] 2017-01-17 19:48
@vkhoroshko The current master branch now includes `scrollBy`. Will that fully address this issue (I merely skimmed this to see if it's been fully addressed now).

**Comment by JordanMartinez** [comment] 2017-03-17 18:16
The snapshot version of Flowless now includes additional scrolling methods. So, I believe this issue has been resolved.
Please reopen if you think otherwise.

**Comment by grenche** [comment] 2018-06-29 17:04
I'm using `scrollYBy()` to solve this same issue and I also need to use the timer to get it to register the `scrollYBy()` call. Additionally, it seems like after moving the caret, `allParToVisibleParIndex` needs the timer otherwise the index returned will be empty.

The timer trick fixes both of these issues, but because of it, the additional scrolling is pretty jerky. Is there a way to adjust the scroll position without the timer?

Specifically I want the caret to be in the middle of the viewport if possible. A method like `showParagraphAtTop`, but in the middle would be super useful, but I can't seem find anything like that.

**Comment by JordanMartinez** [comment] 2018-06-29 17:11
@grenche Could you provide a TestFX test that easily reproduces the issue every time?

**Comment by grenche** [comment] 2018-06-29 19:24
Here's a demo for the problem with `scrollYBy()`.

````java
import javafx.application.Platform;
import org.fxmisc.flowless.VirtualizedScrollPane;
import org.fxmisc.richtext.CodeArea;
import org.fxmisc.richtext.LineNumberFactory;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

import java.util.Timer;
import java.util.TimerTask;

public class BugFix extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        final CodeArea codeArea = new CodeArea();
        codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));
        codeArea.replaceText(getText());
        codeArea.showParagraphAtTop(0);

        final BorderPane root = new BorderPane(new VirtualizedScrollPane<>(codeArea));
        final Scene scene = new Scene(root, 600, 400);
        primaryStage.setScene(scene);
        primaryStage.show();

        // With the first method, the scroll happens with a small delay (more obvious with a longer delay or styled text)
        // and with the second one there is no scroll at all.
        moveCaretWithTimer(codeArea);
//        moveCaretWithoutTimer(codeArea);
    }

    private String getText() {
        final StringBuilder sb = new StringBuilder();

        for (int i = 0; i < 200; i++) {
            sb.append("This is a line of text.\n");
        }

        return sb.toString();
    }

    private void moveCaretWithTimer(CodeArea codeArea) {
        codeArea.moveTo(100, 0);
        codeArea.requestFollowCaret();

        new Timer().schedule(new TimerTask() {
            public void run() {
                Platform.runLater(() -> {
                    codeArea.scrollYBy(100);
                });
            }
        }, 100);
    }

    private void moveCaretWithoutTimer(CodeArea codeArea) {
        codeArea.moveTo(100, 0);
        codeArea.requestFollowCaret();
        codeArea.scrollYBy(100);
    }
}
````

You can replace `codeArea.scrollYBy(100);` with `System.out.println(codeArea.allParToVisibleParIndex(codeArea.getCurrentParagraph()).get())` in both methods and you should get 24 for the first one and an exception for the second one.

**Comment by JordanMartinez** [comment] 2018-06-30 02:51
Thanks! I can further investigate this tomorrow.

**Comment by JordanMartinez** [comment] 2018-06-30 16:40
@grenche The workaround is trivial:
````java
area.moveTo(location);
area.requestFollowCaret();
area.layout();
area.scrollYBy(amount);
````

Here's why it happens. `requestFollowCaret()` sets a flag that, in the next layout call, the viewport should scroll to where the caret is. Thus, upon that method's return, the viewport is not currently displaying the caret at that location. Also, `area.scrollYBy(amount)` does not force the viewport to scroll immediately. It, too, sets a flag that, upon the next layout call, the viewport should redisplay a view that is scrolled by the given amount. 
In the area's `layoutChildren()`, the viewport is resized (which lays it out again and scrolls by the given amount) and then the follow caret is applied (which causes the viewport to scroll to the mouse). Thus, the first actually overrides the second. By using the workaround above, it forces the code to work in the expected order.

**Comment by JordanMartinez** [comment] 2018-06-30 17:11
There are numerous ways to scroll the viewport. We'll refer to these "multiple viewport-scrolling methods" as `MVSM` for brevity. The entire list is below:
- `moveTo` + `requestFollowCaret` - scrolls to the new caret location
- `scrollXBy`, `scrollYBy`, and `scrollBy` - scrolls the viewport by a given amount
- `showParagrapAtTop/Bottom` - scrolls the viewport to the given paragraph
- `showParagraphInViewport` - insures the paragraph is being displayed in the viewport (I think this will scroll the minimum amount before the paragraph is either at the top or bottom of the viewport, depending on whether the paragraph is beyond the "top" or "bottom" of the viewport)

In the following example, the rules for the fix don't seem that hard:
````java
// in one method
area.moveTo(location); area.requestFollowCaret();
area.scrollYBy(amount1);
// in a later method
area.scrollYBy(amount2);
````
It seems clear that we'd first move to the caret location, and then scroll Y by `amount1 + amount2`. This idea should also apply in the following code:
````java
// in one method
area.showParagraphAtTop(parIdx);
// in a later method
area.scrollYBy(amount);
````
However, the next example isn't as trivial. Let's say one has the following code. The question is, how should the viewport be scrolled?
````java
// in one method
area.moveTo(location); area.requestFollowCaret();
area.scrollYBy(amount);
// in a later method
area.scrollYBy(amount);
// in some final method
area.showParagraphAtTop(0);
````
Should the viewport scroll to the first paragraph? Or should it scroll to the caret? Should the `scrollYBy` calls be done after scrolling to the caret if that's what "win?"

MVSM, excluding `scrollBy` are "terminating" methods in that they do not further modify the scroll amount. `Scroll[_/X/Y]By` methods are composing methods in that they do further modify the scroll amount.
So, there are a few strategies that come to mind for how we could resolve this:
- Last "terminating" call wins. If a terminating call is called, it removes any previous scroll compositions (i.e. `scrollBy` calls) and sets how the "initial" scroll amount will be applied. Any scroll composition methods called after that will further alter the scroll. This makes it easier for a programmer, but may lead to hard-to-find bugs later.
- Only allow a single "terminating" call per layout pulse or throw an exception otherwise. This tells the programmer that they need to refactor their code because one terminating call is overriding another. If they really want this, they can force the area to layout its viewport using `area.layout()`.

I think the second one makes more sense.

**Comment by grenche** [comment] 2018-07-02 14:18
@JordanMartinez Thanks so much! `area.layout()` fixed the issue. I also think throwing an exception in the last situation you described makes the most sense.

**Comment by JordanMartinez** [comment] 2018-07-02 16:21
@grenche Would you mind submitting a PR that fixes the code? It would need a few parts:
- a boolean flag to mark whether a terminating call has been called yet that gets set to false when `layoutChildren()` gets called
- a convenience method that will throw that exception if the flag is true, call some underlying terminal method, and then set the flag to true (so that it throws the next time it gets called)
- two doubles (for `x` and `y`) used to mark the additional amount to scroll the viewport after a terminal call.
- reordering the viewport code in `layoutChildren()` to run the `followCaret` code first, then apply the scrolling amounts, and then call the `resizeRelocate`. I believe that would fix the issue and also be the best way to prevent multiple `layout` calls to render the viewport correctly
- a test that insures the code works for the following situations:
    - first terminal call does not throw an exception
    - second terminal call throws an exception
    - scrollBy after each terminal call works as expected

I could help you write the tests or write them myself if you do the other parts.

Another question: should multiple `scrollBy` calls throw an Exception? That will force the developer to track the total amount in their code before it gets applied instead of having to track down multiple `scrollBy` calls throughout multiple methods. If so, that should be factored into the above code, too.

**Closed** 2019-05-23 09:27 UTC
Labels: bug, has workaround
