### ISSUE TITLE
Caret is sometimes rendered on top of and not beside a character on the screen.

### ISSUE THREAD

**Issue by otopba** [FXMisc/RichTextFX#441] opened 2017-02-02 12:14 UTC
Using RichText example I found the following problems: 
1. Wrong caret position
![image](https://cloud.githubusercontent.com/assets/4225279/22548257/ae7c2a3c-e956-11e6-957e-12ede152f6c2.png)

[UPDATED]
2.Duplicate #260 
3.Duplicate #265

**Comment by kuc** [comment] 2017-02-02 13:59
>Enter long text. Scroll bar appears onscreen. When entering each new symbol, the entire text is blinking.

Duplicate of #260

**Comment by JordanMartinez** [comment] 2017-02-03 02:27
@otopba What OS are you using? And which release?

I'm not sure we can do anything about your first point since this is handled by TextFlow. I wonder if your third issue is OS-specific because it doesn't occur in mine (Linux).

**Comment by otopba** [comment] 2017-02-03 09:58
@JordanMartinez I use current master brunch.
MacOs 10.12.3

I noticed that scrolling lag only when using the touchpad, if I use mouse there is no lag

**Comment by JordanMartinez** [comment] 2017-02-03 15:57
@otopba Is that a duplicate of #265? Or a different issue entirely?

**Comment by otopba** [comment] 2017-02-03 16:01
@JordanMartinez  
Yes, it seems that this is the same thing.

**Comment by JordanMartinez** [comment] 2017-02-03 16:11
@otopba ok, could you update this issue's title to just the 1st issue you found and update your first comment to note the duplicates for new readers so they can skip the first initial comments in this thread?

**Closed** 2019-05-23 09:31 UTC
Labels: enhancement
