### ISSUE TITLE
Not recognise combining keys on linux

### ISSUE THREAD

**Issue by Silveriomrs** [FXMisc/RichTextFX#643] opened 2017-11-15 16:07 UTC
Using BlueJ it is not possible in the new versions to type characters like 'á' 'Á'. Ó í ...
Spanish characters. Even on comments. The only way to be able to do it, is copying it from an external editor and paste it into the code.

To type such characters, Spanish keyboard do not use modifier, but pressing the special character '´' available in spanish Keybards and followed by the character that has to get it. for example: ' ´ '+' a ' = á

On CentOS, Linux Mint, in a KDE or Cinnamon environment, I can set my keyboard layout to spanish, and the ñ key (marked as semicolon on my keyboard) does work as expected. However, symbols requiring a combining key (á etc) do not work in the editor, although they do work in the rest of the interface.

This appears therefore to be a RichTextFX bug - it does not recognise combining keys on Linux. However, as I mentioned, I can type ñ and it is correctly recognised. We should look into this further and consider trying to fix the problem in RichTextFX (and push the fix upstream).

**Comment by JordanMartinez** [comment] 2017-11-15 20:54
Duplicate of #280.

**Closed by JordanMartinez** 2017-11-15 20:54 UTC
Labels: duplicate
