### ISSUE TITLE
addEventHandler(MouseOverTextEvent.MOUSE_OVER_TEXT_BEGIN, ... ) is not working anymore

### ISSUE THREAD

**Issue by ouaibsky** [FXMisc/RichTextFX#671] opened 2018-01-16 08:28 UTC
Hi
Starting with release 0.8.1, the API
```java
codearea.addEventHandler(MouseOverTextEvent.MOUSE_OVER_TEXT_BEGIN, ...);
```
is triggering an exception (works fine with 0.8.0)
```java
java.lang.ExceptionInInitializerError: null
	at org.fxmisc.richtext.GenericStyledArea.lambda$null$40(GenericStyledArea.java:1374) ~[richtextfx-0.8.1.jar:0.8.1]
	at org.reactfx.util.Right.unify(Either.java:265) ~[reactfx-2.0-M5.jar:na]
	at org.fxmisc.richtext.GenericStyledArea.lambda$null$41(GenericStyledArea.java:1372) ~[richtextfx-0.8.1.jar:0.8.1]
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.EventStream$1.lambda$observeInputs$1(EventStream.java:424) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.FilterStream.lambda$observeInputs$0(FilterStream.java:20) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.DistinctStream.lambda$observeInputs$0(DistinctStream.java:23) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.EventStream$1.lambda$observeInputs$1(EventStream.java:424) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57) ~[reactfx-2.0-M5.jar:na]
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18) ~[reactfx-2.0-M5.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventQueue.fire(EventQueue.java:48) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.handleEnterExit(Scene.java:3676) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3742) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:na]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: EventType "MOUSE_OVER_TEXT_ANY"with parent "EVENT" already exists
	at javafx.event.EventType.register(EventType.java:186) ~[jfxrt.jar:na]
	at javafx.event.EventType.<init>(EventType.java:128) ~[jfxrt.jar:na]
	at org.fxmisc.richtext.event.MouseOverTextEvent.<clinit>(MouseOverTextEvent.java:19) ~[richtextfx-0.8.1.jar:0.8.1]
	... 77 common frames omitted
```

Christophe

**Comment by JordanMartinez** [comment] 2018-01-16 18:32
Duplicate of #634. Use the snapshot release for right now until the next one comes out.

**Closed by JordanMartinez** 2018-01-16 18:32 UTC
