### ISSUE TITLE
Feature Request: RichTextField

### ISSUE THREAD

**Issue by SkyAphid** [FXMisc/RichTextFX#764] opened 2018-06-30 22:49 UTC
## Desired Feature

RichTextFX should have built-in support for TextFields (rather than entire TextAreas) that only contain a single line, rather than having multi-line capabilities. 

Personally, I'd prefer just a setMultiline(false) on the current text areas rather than an entirely new TextField class. I think it'd save you time. The reason why is because it's not like a TextField really offers much custom functionality, plus it'd make it easier on my end because I can treat both the same, minus just setting a value to false.

## Current Workarounds

See #763 

## Implementation Costs

It shouldn't be that hard to make since a lot of the baseline editing functionality already exists in RichTextFX, it's more of a matter of the developers having time to do it. From my outsiders viewpoint, anyway.

**Comment by SkyAphid** [comment] 2018-07-01 03:54
I hope I did this well enough for you. Let me know if you want it edited at all.

BTW, is there an ETA on the next release of RichTextFX? I really appreciate your work on the API along with being patient and helping me out as well. Thanks again.

**Comment by JordanMartinez** [comment] 2018-07-01 05:39
> I hope I did this well enough for you. Let me know if you want it edited at all.

Thanks. It works fine. A lot of the implementation costs aren't clear unless you're already very familiar with the inner workings of this project.

Implementation Costs:
- Port a subset of GenericStyledArea's code to a Field class
    - The "viewport" would be a variant of `ParagraphBox` that has no index and that implements `Virtualized` and which is wrapped in a VirtualizedScrollPane. This could be changed to just a regular ScrollPane, but if one wanted to have a field and area interact with one another, it would be harder to do that and the API would be different between the two. So I don't think I support that.
    - The "model" document would be a single `Paragraph`. Although `StyledDocument` could be used to make it easier to work with the area version, it would take up unneeded memory. Plus, the paragraph could easily be 'wrapped' back into the `StyledDocument` context when needed.
    - The multiple caret/selection and multi-text-change would also need to work for a field
    - A subset of `GenericStyledAreaBehavior` would be created for the field's default behavior
- Update API to be shared between both area and field where possible (e.g. `insertText()` should work for both, but `replaceText` would be different for the area as it would require a `StyledDocument` whereas the field would require a `Paragraph`)
- Make a copy of a subset of the area tests and create instances of such tests for the field to insure it works properly and doesn't cause regressions
- (Optional) Provide API to easily convert one instance to another (field to area and vice versa)

> Personally, I'd prefer just a setMultiline(false) on the current text areas rather than an entirely new TextField class. I think it'd save you time. The reason why is because it's not like a TextField really offers much custom functionality, plus it'd make it easier on my end because I can treat both the same, minus just setting a value to false.

`setMultiline(false)` would be easier, but it wouldn't be the best code. This feature isn't really a high priority because a workaround exists, but the feature would still be desirable.

> BTW, is there an ETA on the next release of RichTextFX? I really appreciate your work on the API along with being patient and helping me out as well. Thanks again.

I can turn the current snapshot into a release. Really, I'm not focused on this project right now as I'm currently working on Scala related things.

**Comment by SkyAphid** [comment] 2018-07-01 07:53
Well, there's no rush. When you get some time, if you can fix #761 (or let me know how to get around it), I'll probably be good to go for [a release on what I've been making with RichTextFX. ](https://github.com/SkyAphid/JDialogue). I'll keep my eyes posted on the project, so no rush on getting that done. Great work and good luck to you!

**Comment by JordanMartinez** [comment] 2018-07-02 15:50
Do you want to add your project to the list of "Who uses RichTextFX?" on the ReadMe? It's basically free publicity.

**Comment by SkyAphid** [comment] 2018-07-02 21:19
How do I submit a PR to the readme? I'm new to actually interacting with the github community. Lol

**Comment by SkyAphid** [comment] 2018-07-02 21:34
Do you mind just linking it on the readme? I have no idea how to do pull requests, it'd probably be faster if you just linked it real quick. Haha. But it's fine if you don't have time

**Comment by JordanMartinez** [comment] 2018-07-02 23:07
- Fork the repo on GitHub by going to the project's main page and click the Fork button
- In a terminal, clone the forked repo: `git clone https://github.com/YourUserName/RichTextFX.git`
- In a terminal, enter the directory of the just-cloned repo: `cd richtextfx`
- open and edit the ReadMe to have `- [Project Title](URL to project)` below last line
- In a terminal, commit the change: `git commit -m "Added [project name]"
- In a terminal, push the change to your repo: `git push`
- return to original RTFX project on GitHub and you'll see an option to open a PR. Click that button
- Update the PR title to say "Add [project name] to list of who uses RTFX" and delete PR body's contents
- Click "Submit PR"

**Comment by SkyAphid** [comment] 2018-07-03 10:21
I think I managed to do it? Let me know. Lol ; p

**Comment by JordanMartinez** [comment] 2018-07-03 17:20
I haven't received a notification of any PR being submitted by you. Check the GitHub docs and follow them to insure you've done it properly.

**Comment by SkyAphid** [comment] 2018-07-04 03:57
I think I got it for real this time. Sorry about that. Haha

**Comment by Jugen** [comment] 2020-01-15 09:20
Resolved via PR #894

**Closed by Jugen** 2020-01-15 09:20 UTC
Labels: enhancement
